package eu.kanade.tachiyomi.extension.ar.mangalek;

/* This class is generated by JADX */
public final class R {

    public static final class mipmap {
        public static final int ic_launcher = 2130771968;
    }
}
